@ECHO OFF
call conda activate biocapsule
python src/face.py -d vggface2_00 -m facenet -gpu 0
python src/face.py -d vggface2_01 -m arcface -gpu 0
python src/face.py -d vggface2_01 -m facenet -gpu 0
python src/face.py -d vggface2_02 -m arcface -gpu 0
python src/face.py -d vggface2_02 -m facenet -gpu 0
python src/face.py -d vggface2_03 -m arcface -gpu 0
python src/face.py -d vggface2_03 -m facenet -gpu 0
python src/face.py -d vggface2_04 -m arcface -gpu 0
python src/face.py -d vggface2_04 -m facenet -gpu 0
python src/face.py -d vggface2_05 -m arcface -gpu 0
python src/face.py -d vggface2_05 -m facenet -gpu 0
python src/face.py -d vggface2_06 -m arcface -gpu 0
python src/face.py -d vggface2_06 -m facenet -gpu 0
python src/face.py -d vggface2_07 -m arcface -gpu 0
python src/face.py -d vggface2_07 -m facenet -gpu 0
python src/face.py -d vggface2_08 -m arcface -gpu 0
python src/face.py -d vggface2_08 -m facenet -gpu 0
python src/face.py -d vggface2_09 -m arcface -gpu 0
python src/face.py -d vggface2_09 -m facenet -gpu 0
python src/face.py -d vggface2_10 -m arcface -gpu 0
python src/face.py -d vggface2_10 -m facenet -gpu 0
python src/face.py -d vggface2_11 -m arcface -gpu 0
python src/face.py -d vggface2_11 -m facenet -gpu 0
python src/face.py -d vggface2_12 -m arcface -gpu 0
python src/face.py -d vggface2_12 -m facenet -gpu 0
python src/face.py -d vggface2_13 -m arcface -gpu 0
python src/face.py -d vggface2_13 -m facenet -gpu 0
python src/face.py -d vggface2_14 -m arcface -gpu 0
python src/face.py -d vggface2_14 -m facenet -gpu 0
python src/face.py -d vggface2_15 -m arcface -gpu 0
python src/face.py -d vggface2_15 -m facenet -gpu 0
python src/face.py -d vggface2_16 -m arcface -gpu 0
python src/face.py -d vggface2_16 -m facenet -gpu 0
python src/face.py -d vggface2_17 -m arcface -gpu 0
python src/face.py -d vggface2_17 -m facenet -gpu 0
python src/face.py -d vggface2_18 -m arcface -gpu 0
python src/face.py -d vggface2_18 -m facenet -gpu 0
python src/face.py -d vggface2_19 -m arcface -gpu 0
python src/face.py -d vggface2_19 -m facenet -gpu 0
PAUSE